### ISSUE TITLE
how to show indicatorin the canvas?

### ISSUE THREAD

**Issue by tiger2014** [Indemos/Canvas#1]
Hi Indemos,

I want to add some indicators, such as MACD, RSI, and so on, into the canvas. How to do it?

**Comment by artemiusgreat** [comment]
Each canvas can display multiple time series, each time series can have its own type, e.g. candle, bar, line, or some custom shape. 
When you define the structure of the canvas, you can specify how many canvases you need, how many time series each of them will have, their color and shape. 

There is a sample showing exactly this. 

```
points.Add(new GroupModel
{
  Index = DateTime.Now.Ticks,
  Groups = new Dictionary<string, IGroupModel>
  {
    ["Bars"] = new GroupModel                                      // Canvas #1
    { 
      Groups = new Dictionary<string, IGroupModel> 
      { 
        ["MainSeries"] = new BarGroupModel { Value = point }        // The only time series on Canvas #1 - Bar shape
      } 
    },
    ["Lines"] = new GroupModel                                    // Canvas #2
    { 
      Groups = new Dictionary<string, IGroupModel> 
      { 
        ["MACD"] = new LineGroupModel { Value = point },     // Both time series on Canvas #2 have Line shape
        ["RSI"] = new LineGroupModel { Value = point } 
      } 
    },
    ["Candles"] = new GroupModel                                // Canvas #3
    { 
      Groups = new Dictionary<string, IGroupModel> 
      { 
        ["MainSeries"] = new CandleGroupModel { Value = candle },     // One time series is a Candle, second - Line
        ["MovingAverage"] = new LineGroupModel { Value = point } 
      } 
    }
  }
})
```

This sample is already a part of thtis repository, you just need to start the app and go to this page. 
https://github.com/Indemos/Canvas/blob/main/Samples/Pages/Chart.razor.cs 

When you run the sample above, you should see the following. 
It has an example of multiple series within each canvas viewport, e.g. candles + arrows or line + line. 

![image](https://user-images.githubusercontent.com/5140879/171971149-b13b6a13-280a-4e59-a899-5f6dc215a3be.png)

**Comment by artemiusgreat** [comment]
Alternatively, you can copy-paste one of [these](https://github.com/Indemos/Canvas/tree/main/Canvas.Core/Models/Groups) classes and create a custom drawer that can render arbitrary number of Y values for each X index. After this you'd be able to use code sample from the [home page](https://github.com/Indemos/Canvas#data-source-structure) 

```
<CanvasWebView @ref="ViewControl"></CanvasWebView>

@code
{
  public CanvasWebView ViewControl { get; set; }

  protected override async Task OnAfterRenderAsync(bool setup)
  {
    var points = Enumerable.Range(1, 100).Select(i => new CustomMultiplePointsModel
    {
      Index = i,
      Value = new Model { 
        ["Point"] = new Random().Next(-5000, 5000), 
        ["MACD"] = new Random().Next(-5000, 5000), 
        ["MA"] = new Random().Next(-5000, 5000),
        ["RSI"] = new Random().Next(-5000, 5000) 
      }
    } as IPointModel);

    ViewControl.Composer = new Composer
    {
      Name = name,
      Points = points.ToList(),
      Engine = new CanvasEngine(1000, 500)
    };

    ViewControl.Create();
    ViewControl.Update();
  }
}
```

Let me know if you need more details.
